services:
  camunda:
    build: .
    environment:
      JAVA_OPTS: -Djava.security.egd=file:/dev/./urandom -Duser.timezone=Europe/Prague
      CAMUNDA_TOKENS_FILE: /run/secrets/camunda-tokens
    ports:
      - "8080:8080"
    network_mode: "host"
    secrets:
      - camunda-tokens

secrets:
  camunda-tokens:
    file: camunda-tokens.json